avoid calling memset with zero length
This avoids the following build error:

In file included from /usr/include/string.h:638:0,
                 from ./include/opa_user.h:77,
                 from psm_user.h:67,
                 from psm_diags.c:56:
In function 'memset',
    inlined from 'memcpy_check_one.constprop.4' at psm_diags.c:278:8,
    inlined from 'memcpy_check_size.constprop.2' at psm_diags.c:335:30,
    inlined from 'psmi_test_memcpy.constprop.1' at psm_diags.c:230:6,
    inlined from 'psmi_diags' at psm_diags.c:84:25:
/usr/include/bits/string3.h:81:30: error: call to
'__warn_memset_zero_len' declared with attribute warning: memset used
with constant zero length parameter; this could be due to transposed
parameters [-Werror]
       __warn_memset_zero_len ();
                              ^